### ISSUE TITLE
pip install torchlars [CUDA 12 Error]

### ISSUE THREAD

**Issue by BedirYilmaz** [kakaobrain/torchlars#22]
Hi, I have encountered the following error while installing torchlars

```
pc@host:~/Code/byol_exp$ pip install torchlars
Defaulting to user installation because normal site-packages is not writeable
Collecting torchlars
  Downloading torchlars-0.1.2.tar.gz (6.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/pc/.local/lib/python3.10/site-packages (from torchlars) (1.12.1+cu113)
Requirement already satisfied: typing-extensions in /home/pc/.local/lib/python3.10/site-packages (from torch->torchlars) (4.4.0)
Building wheels for collected packages: torchlars
  Building wheel for torchlars (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
        warnings.warn(
      /usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      /home/pc/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/torchlars
      copying torchlars/__version__.py -> build/lib.linux-x86_64-3.10/torchlars
      copying torchlars/lars.py -> build/lib.linux-x86_64-3.10/torchlars
      copying torchlars/__init__.py -> build/lib.linux-x86_64-3.10/torchlars
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9yrcqs_t/torchlars_1ded9320001f4e77ac34912819da31e0/setup.py", line 15, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/pc/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "/home/pc/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.0) mismatches the version that was used to compile
      PyTorch (11.3). Please make sure to use the same CUDA versions.
```

Does this mean that the CUDA 12 is not supported yet?

Thank you

**Comment by ZongYingLi** [comment]
Excuse me, how to solve the error information, did you find the useful solution?
